# Generated by Django 4.2 on 2025-01-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camerafeed_camerafeed_unique_feed_per_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerafeed',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
