# Generated by Django 4.2 on 2024-12-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['label']},
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='zone',
            new_name='zones',
        ),
    ]
