# Generated by Django 4.2.16 on 2024-11-23 13:14
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        CreateExtension('vector'),
        # VectorExtension()
    ]
